### PR TITLE
fix(video): validate video args

### LINKED ISSUE #1451: PlaywrightException thrown if only RecordVideoDir is specified
According to the [documentation](https://playwright.dev/dotnet/docs/videos?_highlight=video), it should be possible to specify only a directory to capture videos with Playwright:

```csharp
var context = await browser.NewContextAsync(new BrowserNewContextOptions
{
    RecordVideoDir = "videos"
});
// Make sure to close, so that videos are saved.
await context.CloseAsync();
```

However, upon attempting to run a test in this way with `Microsoft.Playwright` version `1.11.1-alpha-2`, a `PlaywrightException` is thrown similar to the below:

```
  Error Message:
   Microsoft.Playwright.PlaywrightException : recordVideo.size: expected object, got null
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 202
   at Microsoft.Playwright.Browser.NewContextAsync(Nullable`1 acceptDownloads, Nullable`1 ignoreHTTPSErrors, Nullable`1 bypassCSP, ViewportSize viewportSize, ScreenSize screenSize, String userAgent, Nullable`1 deviceScaleFactor, Nullable`1 isMobile, Nullable`1 hasTouch, Nullable`1 javaScriptEnabled, String timezoneId, Geolocation geolocation, String locale, IEnumerable`1 permissions, IEnumerable`1 extraHTTPHeaders, Nullable`1 offline, HttpCredentials httpCredentials, Nullable`1 colorScheme, String recordHarPath, Nullable`1 recordHarOmitContent, String recordVideoDir, RecordVideoSize recordVideoSize, Proxy proxy, String storageState, String storageStatePath) in /_/src/Playwright/Browser.cs:line 79
   at Microsoft.Playwright.Browser.NewPageAsync(Nullable`1 acceptDownloads, Nullable`1 ignoreHTTPSErrors, Nullable`1 bypassCSP, ViewportSize viewportSize, ScreenSize screenSize, String userAgent, Nullable`1 deviceScaleFactor, Nullable`1 isMobile, Nullable`1 hasTouch, Nullable`1 javaScriptEnabled, String timezoneId, Geolocation geolocation, String locale, IEnumerable`1 permissions, IEnumerable`1 extraHTTPHeaders, Nullable`1 offline, HttpCredentials httpCredentials, Nullable`1 colorScheme, String recordHarPath, Nullable`1 recordHarOmitContent, String recordVideoDir, RecordVideoSize recordVideoSize, Proxy proxy, String storageState, String storageStatePath) in /_/src/Playwright/Browser.cs:line 138
```

Specifying an explicit `RecordVideoSize` value to the `RecordVideoSize` property resolves the issue.

Playwright should either set a size internally so that the documentation is accurate, or the documentation be updated to specify that the size is required.

### PR DESCRIPTION
**Pull request by kblok**
closes #1451

### CODE REVIEW

File: src/Playwright/Transport/Channels/BrowserChannel.cs [hunk 1]
```diff
@@ -52,27 +52,39 @@ internal override void OnMessage(string method, JsonElement? serverParams)
...
-            args.Add("colorScheme", colorScheme);
-            args.Add("deviceScaleFactor", deviceScaleFactor);
+            if (recordVideoSize != null && string.IsNullOrEmpty(recordVideoDir))
+            {
+                throw new PlaywrightException("\"RecordVideoSize\" option requires \"RecordVideoDir\" to be specified");
+            }
+
+            var args = new Dictionary<string, object>
+            {
+                { "acceptDownloads", acceptDownloads },
```
Comment (pavelfeldman) [inline src/Playwright/Transport/Channels/BrowserChannel.cs:62]: Why did this change?

File: src/Playwright.Tests/ScreencastTests.cs [hunk 2]
```diff
@@ -21,9 +19,15 @@ public ScreencastTests(ITestOutputHelper output) : base(output)
         }
 
         [PlaywrightTest("screencast.spec.ts", "videoSize should require videosPath")]
-        [Fact(Skip = "We are not using old properties")]
-        public void VideoSizeShouldRequireVideosPath()
+        [SkipBrowserAndPlatformFact(skipWebkit: true, skipWindows: true)]
```
Comment (avodovnik) [inline src/Playwright.Tests/ScreencastTests.cs:22]: Why are we skipping Windows? Is this an upstream thing as well? Just so we document it...

**Review by avodovnik — APPROVED** [review]

File: src/Playwright.Tests/ScreencastTests.cs (hunk 2 above)
Comment (kblok) [reply src/Playwright.Tests/ScreencastTests.cs]: done!
