### PR TITLE
Fix PDF generation

### LINKED ISSUE #884: Error when generating pdf
When trying to generate a pdf after updating to latest nuget package (0.111.2), I receive the following error:
`PlaywrightSharpException: options.format.toLowerCase is not a function`

after calling it like this:
```
var result = await page.GetPdfAsync(null, pdfConversionOptions.Scale, pdfConversionOptions.DisplayHeaderFooter, pdfConversionOptions.HeaderTemplate, pdfConversionOptions.FooterTemplate,
  pdfConversionOptions.PrintBackground, pdfConversionOptions.Landscape, pdfConversionOptions.PageRanges, pdfConversionOptions.Format, pdfConversionOptions.Width, pdfConversionOptions.Height,
  pdfConversionOptions.Margin, pdfConversionOptions.PreferCSSPageSize);
```

I tried also specifying directly `PaperFormat.Letter` for example but I receive the same error...

### PR DESCRIPTION
**Pull request by kblok**
closes #884

### CODE REVIEW

File: src/PlaywrightSharp/Page.cs [hunk 1]
```diff
@@ -701,6 +701,11 @@ public async Task<IResponse> WaitForResponseAsync(Func<IResponse, bool> predicat
             Margin margin = null,
             bool preferCSSPageSize = false)
         {
+            if (BrowserContext.BrowserName != "chromium")
```
Comment (Meir017) [inline src/PlaywrightSharp/Page.cs:704]: do we have a constant for this?
